console.log("hi");
const x=4;
try {
    x=5;
    console.log(X);
} catch (error) {
    console.log("error");
    console.log(error.message)
    
}
console.log("hello");